spring.application.name=Journal App
spring.data.mongodb.uri=mongodb+srv://aniketmagade3296_db_use:gUCxZe9FIUKvmeRe@cluster-aniket.flue29g.mongodb.net/?appName=cluster-aniket
spring.data.mongodb.database=journalDb
#spring.data.mongodb.auto-index-creation=true